### ISSUE TITLE
Error reading manifest

### ISSUE THREAD

**Issue by 3773** [Drakulix/unifi-dns-gen#1]
when I run the line I get an error
`
# > podman run --name unifi-dns-gen -e UNIFI_BASEURL=https://192.168.1.1 -e UNIFI_USERNAME=my-UniFi-Account -e UNIFI_PASSWORD=My-UniFi-Password -e HOSTS_FILE="/hosts/unifi.hosts -v "/mnt/data/hosts:/hosts" -it --rm docker.pkg.github.com/drakulix/unifi-dns-gen/unifi-dns-gen:latest
`

> Trying to pull docker.pkg.github.com/drakulix/unifi-dns-gen/unifi-dns-gen:latest...
>   unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
> Error: unable to pull docker.pkg.github.com/drakulix/unifi-dns-gen/unifi-dns-gen:latest: unable to pull image: Error initializing source docker://docker.pkg.github.com/drakulix/unifi-dns-gen/unifi-dns-gen:latest: Error reading manifest latest in docker.pkg.github.com/drakulix/unifi-dns-gen/unifi-dns-gen: unauth
orized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.

In my GitHub account I already have a personal access token under the settings
created. Where do I have to insert this?

**Comment by 3773** [comment]
syntax error...

> podman run --name unifi-dns-gen -e UNIFI_BASEURL=https://192.168.1.1 -e UNIFI_USERNAME=my-UniFi-Account -e UNIFI_PASSWORD=My-UniFi-Password -e HOSTS_FILE=/hosts/unifi.hosts -v /mnt/data/hosts:/hosts -it --rm docker.pkg.github.com/drakulix/unifi-dns-gen/unifi-dns-gen:latest

**Comment by Drakulix** [comment]
Oh wow, my small side project from last week is already used by someone...
Glad you figured out your mistake, but the README still contains an error.

Since github deprecated packages inside repositories and instead moved them to the Github Container Registry, that image should be `ghcr.io/drakulix/unifi-dns-gen:latest` instead of `docker.pkg.github.com/drakulix/unifi-dns-gen/unifi-dns-gen:latest`.

Without this issue, it would probably took me much longer to notice that! Fixed in 5a84a8643d2dc08471a5ce0c3ad4f090c820b9f0 .

If any other issues come up, please let me know.
